# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15service/service.proto\x12\x07\x65xample\"D\n\x0cInferRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\r\n\x05logId\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\t\"C\n\rInferResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\r\n\x05logId\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\t2M\n\x0cInferService\x12=\n\nStartInfer\x12\x15.example.InferRequest\x1a\x16.example.InferResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERREQUEST']._serialized_start=34
  _globals['_INFERREQUEST']._serialized_end=102
  _globals['_INFERRESPONSE']._serialized_start=104
  _globals['_INFERRESPONSE']._serialized_end=171
  _globals['_INFERSERVICE']._serialized_start=173
  _globals['_INFERSERVICE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
